### ISSUE TITLE
Can't generate fem

### ISSUE THREAD

**Issue by Loghonox** [vlukes/dicom2fem#15]
when I try  python dicom2fem/dicom2fem.py -f /home/loghonox/Downloads/EE5A464D.dcm

I have error:

Traceback (most recent call last):
  File "/home/loghonox/Documents/dicom2fem/dicom2fem/dicom2fem.py", line 873, in <module>
    main()
  File "/home/loghonox/Documents/dicom2fem/dicom2fem/dicom2fem.py", line 864, in main
    mw.loadDcm(filename=options.dcmfile)
  File "/home/loghonox/Documents/dicom2fem/dicom2fem/dicom2fem.py", line 562, in loadDcm
    self.dcm_3Ddata = data['data']
KeyError: 'data'

when I try wit folder:

Traceback (most recent call last):
  File "/home/loghonox/Documents/dicom2fem/dicom2fem/dicom2fem.py", line 873, in <module>
    main()
  File "/home/loghonox/Documents/dicom2fem/dicom2fem/dicom2fem.py", line 861, in main
    mw.loadDcmDir()
  File "/home/loghonox/Documents/dicom2fem/dicom2fem/dicom2fem.py", line 438, in loadDcmDir
    dcr = dcmreader.DicomReader(os.path.abspath(self.dcmdir),
  File "/home/loghonox/anaconda3/lib/python3.9/site-packages/io3d/dcmreaddata.py", line 165, in __init__
    self.set_series_number(self.series_number)
  File "/home/loghonox/anaconda3/lib/python3.9/site-packages/io3d/dcmreaddata.py", line 179, in set_series_number
    raise ValueError(
ValueError: No data for series number 2 in directory /home/loghonox/Downloads

any solution?

**Comment by vlukes** [comment]
Hi @Loghonox,

`-f` option is used to load DCM files generated by dicom2fem. It is a file in Matlab format containing a 3D matrix and voxel size information. You probably need to load a series of dicom files stored in a directory. Then use `-d` option:

```
python dicom2fem/dicom2fem.py -d /home/loghonox/Downloads/
``` 

Regards
Vladimir
